import { Holiday } from '@/types/holiday';

export const mockHolidays: Holiday[] = [
  {
    id: 'mock-2024-01-01',
    date: '2024-01-01',
    name: '신정',
    isHoliday: true,
    isNonWorkingDay: true,
    isSubstituteHoliday: false,
    holidayType: 'public',
    source: 'mock',
    overrideStatus: 'none',
    updatedAt: Date.now(),
  },
  {
    id: 'mock-2024-02-09',
    date: '2024-02-09',
    name: '설날 연휴',
    isHoliday: true,
    isNonWorkingDay: true,
    isSubstituteHoliday: false,
    holidayType: 'public',
    source: 'mock',
    overrideStatus: 'none',
    updatedAt: Date.now(),
  },
  {
    id: 'mock-2024-02-10',
    date: '2024-02-10',
    name: '설날',
    isHoliday: true,
    isNonWorkingDay: true,
    isSubstituteHoliday: false,
    holidayType: 'public',
    source: 'mock',
    overrideStatus: 'none',
    updatedAt: Date.now(),
  },
  {
    id: 'mock-2024-02-11',
    date: '2024-02-11',
    name: '설날 연휴',
    isHoliday: true,
    isNonWorkingDay: true,
    isSubstituteHoliday: false,
    holidayType: 'public',
    source: 'mock',
    overrideStatus: 'none',
    updatedAt: Date.now(),
  },
  {
    id: 'mock-2024-02-12',
    date: '2024-02-12',
    name: '대체공휴일(설날)',
    isHoliday: true,
    isNonWorkingDay: true,
    isSubstituteHoliday: true,
    holidayType: 'substitute',
    source: 'mock',
    overrideStatus: 'none',
    updatedAt: Date.now(),
  },
  {
    id: 'mock-2024-03-01',
    date: '2024-03-01',
    name: '삼일절',
    isHoliday: true,
    isNonWorkingDay: true,
    isSubstituteHoliday: false,
    holidayType: 'public',
    source: 'mock',
    overrideStatus: 'none',
    updatedAt: Date.now(),
  },
  {
    id: 'mock-2024-05-01',
    date: '2024-05-01',
    name: '근로자의 날',
    isHoliday: true,
    isNonWorkingDay: true,
    isSubstituteHoliday: false,
    holidayType: 'laborDay',
    source: 'mock',
    overrideStatus: 'none',
    updatedAt: Date.now(),
  },
  {
    id: 'mock-2024-05-05',
    date: '2024-05-05',
    name: '어린이날',
    isHoliday: true,
    isNonWorkingDay: true,
    isSubstituteHoliday: false,
    holidayType: 'public',
    source: 'mock',
    overrideStatus: 'none',
    updatedAt: Date.now(),
  },
  {
    id: 'mock-2024-05-06',
    date: '2024-05-06',
    name: '대체공휴일(어린이날)',
    isHoliday: true,
    isNonWorkingDay: true,
    isSubstituteHoliday: true,
    holidayType: 'substitute',
    source: 'mock',
    overrideStatus: 'none',
    updatedAt: Date.now(),
  },
];
